name: Build and upload release (windows)

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: buranko
  ARCHIVE_NAME: buranko_windows-x64.zip

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build application
        run: |
          cargo build --release
          cd target/release
          ls
          7z a -tzip $ARCHIVE_NAME $APP_NAME.exe
          mv $ARCHIVE_NAME ../../
        shell: bash

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
